package index

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCollectEligibleGoFilesAndFingerprint(t *testing.T) {
	root := t.TempDir()
	mustWrite := func(path, body string) {
		t.Helper()
		full := filepath.Join(root, path)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatalf("mkdir for %s: %v", path, err)
		}
		if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
	}

	mustWrite("main.go", "package main\nfunc main(){}\n")
	mustWrite("sub/util.go", "package sub\nfunc Util(){}\n")
	mustWrite("x_test.go", "package main\n")
	mustWrite("vendor/ignored.go", "package vendor\n")
	mustWrite("testdata/ignored.go", "package testdata\n")
	mustWrite(".cache/ignored.go", "package cache\n")
	mustWrite("generated.go", "// Code generated by x. DO NOT EDIT.\npackage main\n")

	files, err := CollectEligibleGoFiles(root)
	if err != nil {
		t.Fatalf("CollectEligibleGoFiles() error = %v", err)
	}
	if len(files) != 2 {
		t.Fatalf("expected 2 eligible files, got %d", len(files))
	}
	if files[0].RelPath != "main.go" || files[1].RelPath != "sub/util.go" {
		t.Fatalf("unexpected rel paths: %+v", files)
	}
	if files[0].Lines == 0 || files[0].Hash == "" {
		t.Fatalf("expected lines/hash to be populated: %+v", files[0])
	}

	fp, count, err := CurrentFingerprint(root)
	if err != nil {
		t.Fatalf("CurrentFingerprint() error = %v", err)
	}
	if count != 2 || fp == "" {
		t.Fatalf("unexpected fingerprint result count=%d fp=%q", count, fp)
	}

	fp2 := ComputeFingerprint(files)
	if fp2 != fp {
		t.Fatalf("ComputeFingerprint mismatch: %s vs %s", fp2, fp)
	}
}

func TestCollectEligibleGoFilesError(t *testing.T) {
	if _, err := CollectEligibleGoFiles(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatal("expected walk error")
	}
	if _, _, err := CurrentFingerprint(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatal("expected fingerprint error")
	}
}

func TestComputeFingerprintOrderSensitive(t *testing.T) {
	a := []SourceFile{{RelPath: "a.go", Hash: "1"}, {RelPath: "b.go", Hash: "2"}}
	b := []SourceFile{{RelPath: "b.go", Hash: "2"}, {RelPath: "a.go", Hash: "1"}}
	if ComputeFingerprint(a) == ComputeFingerprint(b) {
		t.Fatal("expected different fingerprints for different order")
	}
}

func TestShouldSkipDir(t *testing.T) {
	root := t.TempDir()
	if !shouldSkipDir(root, filepath.Join(root, ".x"), ".x") {
		t.Fatal("expected hidden dir skip")
	}
	for _, name := range []string{"vendor", "testdata", ".recon"} {
		if !shouldSkipDir(root, filepath.Join(root, name), name) {
			t.Fatalf("expected %s skip", name)
		}
	}
	if shouldSkipDir(root, filepath.Join(root, "pkg"), "pkg") {
		t.Fatal("did not expect pkg skip")
	}
}

func TestIsGeneratedGoFile(t *testing.T) {
	if !isGeneratedGoFile([]byte("// Code generated by tool. DO NOT EDIT.\n")) {
		t.Fatal("expected generated file detection")
	}
	prefix := strings.Repeat("x", 5000)
	if isGeneratedGoFile([]byte(prefix)) {
		t.Fatal("did not expect generated detection for random content")
	}
}
